/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;
import java.sql.*;

/**
 *
 * @author siddhant
 */
public class roomanage extends javax.swing.JFrame {

    /**
     * Creates new form roomanage
     */
    public roomanage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        T2 = new javax.swing.JTextField();
        T3 = new javax.swing.JTextField();
        T4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        s1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Room No.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Room type");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("bed type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tarrif");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));
        getContentPane().add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 100, -1));
        getContentPane().add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 100, -1));
        getContentPane().add(T3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 100, -1));
        getContentPane().add(T4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 100, -1));

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 67, -1));

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 67, -1));

        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, -1));

        s1.setText("Enter Room No.");
        getContentPane().add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 100, -1));

        jButton5.setText("back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 70, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Apurv Pandey\\Documents\\NetBeansProjects\\hotel\\New folder\\Serenity (1).jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 240));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Apurv Pandey\\Documents\\NetBeansProjects\\hotel\\New folder\\blue.jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 500, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        try {
            Class.forName("com.mysql.jdbc.Driver");
         
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost/hotel","root","admin");
        
            Statement stmt=conn.createStatement();
            
            String sql="insert into book values ("+ T1.getText() + ","+ "'" +T2.getText() +"'" +","+ "'" +T3.getText()+"'" +","+ T4.getText() + ")"+";";
            
            stmt.executeUpdate(sql);
            
            System.out.println("SUCCESFULL");
         }
         catch(Exception e)
         {
              System.out.println("ERROR : " + e);
             
         }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
         try {
            Class.forName("com.mysql.jdbc.Driver");
         
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost/hotel","root","admin");
        
            Statement stmt=conn.createStatement();
            
            String sql="update book set room_no="+ T1.getText() + ","+ "room_type="+"'" +T2.getText() +"'" +", bed_type="+ "'" +T3.getText()+"'" +", tarrif="+ T4.getText() + " where room_no="+ T1.getText() +";";
            
            stmt.executeUpdate(sql);
            
            System.out.println("SUCCESFULL");
         }
         catch(Exception e)
         {
              System.out.println("ERROR : " + e);
             
         }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
         
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost/hotel","root","admin");
        
            Statement stmt=conn.createStatement();
            
            String sql="delete from book where room_no="+ T1.getText() + ","+ "room_type="+"'" +T2.getText() +"'" +", bed_type="+ "'" +T3.getText()+"'" +", tarrif="+ T4.getText() + ";";
            
            stmt.executeUpdate(sql);
            
            System.out.println("SUCCESFULL");
         }
         catch(Exception e)
         {
              System.out.println("ERROR : " + e);
             
         }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
         
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost/hotel","root","admin");
        
            Statement stmt=conn.createStatement();
            
            String sql="Select * from book where room_no= "+ s1.getText() +";";
            
            ResultSet rs =stmt.executeQuery(sql);
            
            if(rs.next())
            {
                T1.setText(s1.getText());
                T2.setText(rs.getString("room_type"));
                T3.setText(rs.getString("bed_type"));
                T4.setText(""+rs.getInt("tarrif"));
            }
            
            System.out.println("SUCCESFULL");
            
         }
         catch(Exception e)
         {
              System.out.println("ERROR : " + e);
             
         }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        new my().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(roomanage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(roomanage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(roomanage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(roomanage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new roomanage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField s1;
    // End of variables declaration//GEN-END:variables
}
